name: Build and deploy Python project to Azure Function App

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      target_function:
        description: 'Select the Azure Function App to deploy'
        required: true
        type: choice
        options:
          - ASFunc
          - AScrFunc

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: "." # Path to your web app project, defaults to the repository root
  PYTHON_VERSION: "3.11" # Python version to use (supports 3.6, 3.7, 3.8)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python version
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Zip artifact for deployment
        run: zip -r release.zip ./* -x 'venv/*'

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: "Deploy to Azure Function"
        uses: Azure/functions-action@v1
        id: deploy-to-function
        with:
          app-name: "${{ github.event.inputs.target_function }}"
          slot-name: "Production"
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          scm-do-build-during-deployment: true
          enable-oryx-build: true
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_862067B592794F8A8536F0B28D34495C }}
